name: HueManagerHomeSync
options:
  bundleIdPrefix: com.albaintor
  developmentLanguage: fr
  deploymentTarget:
    iOS: "18.0"
settings:
  base:
    SWIFT_VERSION: 5.10
targets:
  HueManagerHomeSync:
    type: application
    platform: iOS
    sources:
      - Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.albaintor.HueManagerHomeSync
        DEVELOPMENT_TEAM: CMS96L8KZ4
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: HueManagerHomeSync.entitlements
        INFOPLIST_FILE: Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"
        MARKETING_VERSION: "0.7.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: HueManagerHomeSync.entitlements
    attributes:
      SystemCapabilities:
        com.apple.HomeKit:
          enabled: 1
schemes:
  HueManagerHomeSync:
    build:
      targets:
        HueManagerHomeSync: all
    run:
      config: Debug
    archive:
      config: Release
